"""
Django settings for site_stat project.

Generated by 'django-admin startproject' using Django 1.11.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
from os import path, makedirs

BASE_DIR = path.dirname(path.dirname(path.abspath(__file__)))
GRABS_SUBDIR = path.join("files", "grabs")
GRABS_DIR = path.join(BASE_DIR, GRABS_SUBDIR)
REPORTS_SUBDIR = path.join("files", "reports")
REPORTS_DIR = path.join(BASE_DIR, REPORTS_SUBDIR)
ZIPS_SUBDIR = path.join("files", "zips")
ZIPS_DIR = path.join(BASE_DIR, ZIPS_SUBDIR)
if not path.exists(GRABS_DIR):
    makedirs(GRABS_DIR)
if not path.exists(REPORTS_DIR):
    makedirs(REPORTS_DIR)
if not path.exists(ZIPS_DIR):
    makedirs(ZIPS_DIR)

GRAB_SLEEP_TIMEOUT = 60
ZIP_SLEEP_TIMEOUT = 5
REPORT_SLEEP_TIMEOUT = 5
WORKER_CHECK_TIMEOUT = 1


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'c%5pr2lxq+xtaec*jm$s9zq10j4qitpxz3@zak*585gn4_i*z6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

DATA_UPLOAD_MAX_NUMBER_FIELDS = None


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'reports',
    'input_data',
    'workers',
    'daterange_filter'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'site_stat.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'site_stat.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = path.join(BASE_DIR, 'static/')
if not path.exists(STATIC_ROOT):
    makedirs(STATIC_ROOT)

try:
    from settings_local import *  # noqa
except ImportError as e:
    pass
