# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='name',
            field=models.CharField(default='NULL', max_length=200, unique=True, verbose_name='Template name'),
            preserve_default=False,
        ),
    ]
