# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('input_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrabberLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name='Created at')),
                ('filename', models.FileField(upload_to=b'', verbose_name='File')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='input_data.Site', verbose_name='Sitename')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': 'Saved page',
                'verbose_name_plural': 'Saved pages',
            },
        ),
        migrations.CreateModel(
            name='ReportRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_from', models.DateTimeField(verbose_name='From')),
                ('ends_from', models.DateTimeField(verbose_name='Till')),
                ('status', models.IntegerField(choices=[(0, 'In progress'), (2, 'No data'), (1, 'Error'), (3, 'Finished')], default=0, verbose_name='Status')),
                ('filename', models.FileField(upload_to=b'', verbose_name='File')),
                ('sites', models.ManyToManyField(to='input_data.Site', verbose_name='Site list')),
                ('templates', models.ManyToManyField(to='input_data.Template', verbose_name='Templates')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
        migrations.CreateModel(
            name='ZipRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_from', models.DateTimeField(verbose_name='From')),
                ('ends_from', models.DateTimeField(verbose_name='Till')),
                ('status', models.IntegerField(choices=[(0, 'In progress'), (2, 'No data'), (1, 'Error'), (3, 'Finished')], default=0, verbose_name='Status')),
                ('filename', models.FileField(null=True, upload_to=b'', verbose_name='File')),
                ('sites', models.ManyToManyField(to='input_data.Site', verbose_name='Site list')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': 'ZIP',
                'verbose_name_plural': 'ZIPs',
            },
        ),
    ]
