# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grabberlog',
            name='created_at',
            field=models.DateTimeField(verbose_name='Created at'),
        ),
    ]
