# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ziprequest',
            name='delete_sources',
            field=models.BooleanField(default=False, verbose_name='Delete original files from host'),
        ),
    ]
