# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_ziprequest_delete_sources'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grabberlog',
            options={'ordering': ['-id'], 'verbose_name': 'Snapshot', 'verbose_name_plural': 'Snapshots'},
        ),
        migrations.AlterField(
            model_name='reportrequest',
            name='ends_from',
            field=models.DateTimeField(verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='reportrequest',
            name='starts_from',
            field=models.DateTimeField(verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='ziprequest',
            name='ends_from',
            field=models.DateTimeField(verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='ziprequest',
            name='sites',
            field=models.ManyToManyField(to='input_data.Site', verbose_name='Sites'),
        ),
        migrations.AlterField(
            model_name='ziprequest',
            name='starts_from',
            field=models.DateTimeField(verbose_name='Start date'),
        ),
    ]
