# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20170814_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportrequest',
            name='detalisation',
            field=models.IntegerField(choices=[(0, 'By day'), (1, 'By hour'), (2, 'Full')], default=0, verbose_name='Status'),
        ),
    ]
