# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_reportrequest_detalisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportrequest',
            name='detalisation',
            field=models.IntegerField(choices=[(0, 'By day'), (1, 'By hour'), (2, 'Full')], default=0, verbose_name='Detalisation'),
        ),
    ]
