# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrabberLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.FileField(upload_to=b'', verbose_name='Filename')),
            ],
            options={
                'verbose_name': 'Grabber Log',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(unique=True, verbose_name='Site URL')),
                ('name', models.TextField(unique=True, verbose_name='Site name')),
            ],
            options={
                'verbose_name': 'Site',
            },
        ),
        migrations.AddField(
            model_name='grabberlog',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grabber.Site', verbose_name='Site URL'),
        ),
    ]
