# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grabber', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.TextField(unique=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0448\u0430\u0431\u043b\u043e\u043d\u0430')),
            ],
            options={
                'verbose_name': '\u0428\u0430\u0431\u043b\u043e\u043d',
                'verbose_name_plural': '\u0428\u0430\u0431\u043b\u043e\u043d\u044b',
            },
        ),
        migrations.AlterModelOptions(
            name='grabberlog',
            options={'verbose_name': '\u0421\u043e\u0445\u0440\u0430\u043d\u0451\u043d\u043d\u0430\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430', 'verbose_name_plural': '\u0410\u0440\u0445\u0438\u0432'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': '\u0421\u0430\u0439\u0442', 'verbose_name_plural': '\u0421\u0430\u0439\u0442\u044b'},
        ),
        migrations.AlterField(
            model_name='grabberlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u0421\u043e\u0437\u0434\u0430\u043d'),
        ),
        migrations.AlterField(
            model_name='grabberlog',
            name='filename',
            field=models.FileField(upload_to=b'', verbose_name='\u0424\u0430\u0439\u043b'),
        ),
        migrations.AlterField(
            model_name='grabberlog',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grabber.Site', verbose_name='\u0418\u043c\u044f \u0441\u0430\u0439\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.TextField(unique=True, verbose_name='\u0418\u043c\u044f \u0441\u0430\u0439\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='site',
            name='url',
            field=models.TextField(unique=True, verbose_name='\u0410\u0434\u0440\u0435\u0441 \u0441\u0430\u0439\u0442\u0430'),
        ),
        migrations.AddField(
            model_name='templates',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grabber.Site', verbose_name='\u0418\u043c\u044f \u0441\u0430\u0439\u0442\u0430'),
        ),
    ]
