# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabber', '0002_auto_20170805_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_from', models.DateTimeField(verbose_name='\u0421')),
                ('endss_from', models.DateTimeField(verbose_name='\u0414\u043e')),
                ('delete', models.BooleanField(verbose_name='\u0423\u0434\u0430\u043b\u0438\u0442\u044c \u043f\u043e \u0437\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u0438\u044e')),
                ('status', models.IntegerField(choices=[(0, '\u0421\u043e\u0437\u0434\u0430\u043d'), (1, '\u041e\u0448\u0438\u0431\u043a\u0430'), (2, '\u0412\u044b\u043f\u043e\u043b\u043d\u0435\u043d')], default=0, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
                ('filename', models.FileField(upload_to=b'', verbose_name='\u0424\u0430\u0439\u043b')),
                ('sites', models.ManyToManyField(to='grabber.Site', verbose_name='\u0414\u043b\u044f \u0441\u0430\u0439\u0442\u043e\u0432')),
            ],
        ),
        migrations.CreateModel(
            name='ReportRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_from', models.DateTimeField(verbose_name='\u0421')),
                ('endss_from', models.DateTimeField(verbose_name='\u0414\u043e')),
                ('status', models.IntegerField(choices=[(0, '\u0421\u043e\u0437\u0434\u0430\u043d'), (1, '\u041e\u0448\u0438\u0431\u043a\u0430'), (2, '\u0412\u044b\u043f\u043e\u043b\u043d\u0435\u043d')], default=0, verbose_name='\u0423\u0434\u0430\u043b\u0438\u0442\u044c \u043f\u043e \u0437\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u0438\u044e')),
                ('filename', models.FileField(upload_to=b'', verbose_name='\u0424\u0430\u0439\u043b')),
                ('sites', models.ManyToManyField(to='grabber.Site', verbose_name='\u0421\u0430\u0439\u0442\u044b')),
            ],
        ),
        migrations.RenameModel(
            old_name='Templates',
            new_name='Template',
        ),
        migrations.AddField(
            model_name='reportrequest',
            name='templates',
            field=models.ManyToManyField(to='grabber.Template', verbose_name='\u0428\u0430\u0431\u043b\u043e\u043d\u044b'),
        ),
    ]
