# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabber', '0003_auto_20170805_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_from', models.DateTimeField(verbose_name='\u0421')),
                ('ends_from', models.DateTimeField(verbose_name='\u0414\u043e')),
                ('status', models.IntegerField(choices=[(0, '\u041d\u0435 \u043e\u0431\u0440\u0430\u0431\u043e\u0442\u0430\u043d'), (1, '\u041e\u0448\u0438\u0431\u043a\u0430'), (2, '\u0412\u044b\u043f\u043e\u043b\u043d\u0435\u043d')], default=0, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
                ('filename', models.FileField(null=True, upload_to=b'', verbose_name='\u0424\u0430\u0439\u043b')),
                ('sites', models.ManyToManyField(to='grabber.Site', verbose_name='\u0414\u043b\u044f \u0441\u0430\u0439\u0442\u043e\u0432')),
            ],
        ),
        migrations.RemoveField(
            model_name='archiverequest',
            name='sites',
        ),
        migrations.RenameField(
            model_name='reportrequest',
            old_name='endss_from',
            new_name='ends_from',
        ),
        migrations.AlterField(
            model_name='reportrequest',
            name='sites',
            field=models.ManyToManyField(to='grabber.Site', verbose_name='\u0414\u043b\u044f \u0441\u0430\u0439\u0442\u043e\u0432'),
        ),
        migrations.AlterField(
            model_name='reportrequest',
            name='status',
            field=models.IntegerField(choices=[(0, '\u041d\u0435 \u043e\u0431\u0440\u0430\u0431\u043e\u0442\u0430\u043d'), (1, '\u041e\u0448\u0438\u0431\u043a\u0430'), (2, '\u0412\u044b\u043f\u043e\u043b\u043d\u0435\u043d')], default=0, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441'),
        ),
        migrations.DeleteModel(
            name='ArchiveRequest',
        ),
    ]
