# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(choices=[('grab', 'Grab worker'), ('zip', 'Zip worker'), ('report', 'Report worker')], max_length=20, unique=True, verbose_name='Status')),
                ('timeout', models.IntegerField(default=5, verbose_name='Worker timeout')),
                ('next_run', models.DateTimeField(verbose_name='Next run')),
                ('heartbet', models.DateField(verbose_name='Heartbeat')),
            ],
            options={
                'verbose_name': 'Worker',
                'verbose_name_plural': 'Workers',
            },
        ),
    ]
