# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='heartbet',
            new_name='heartbeat',
        ),
    ]
